data_ingestion:
  bucket_name: hotel-reservation-bucket-yashmlops
  bucket_file_name: hotel_reservations.csv
  test_ratio: 0.25

data_processing:
  skewness_threshold: 5
  top_feature_selection : 10
  categorical_columns:
    - type_of_meal_plan
    - room_type_reserved
    - required_car_parking_space
    - market_segment_type
    - booking_status
    - repeated_guest
  numerical_columns:
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - lead_time
    - arrival_year
    - arrival_month
    - arrival_date
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests
